version: '3.1'

services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306'
    environment:
        MYSQL_ROOT_PASSWORD: 12345678
  python:
    image: phonebook-app:latest
    restart: always
    ports:
      - '8000:8000'